[workspace]
members = ["reikura_app", "reikura_gdl", "reikura_gfx", "reikura_tools", "reikura_util"]
default_members = ["reikura_gdl", "reikura_gfx", "reikura_util"]
resolver = "3"

[workspace.dependencies]
reikura_app = { path = "reikura_app" }
reikura_gdl = { path = "reikura_gdl" }
reikura_gfx = { path = "reikura_gfx" }
reikura_util = { path = "reikura_util" }
reikura_tools = { path = "reikura_tools" }

anyhow = "1.0"
memmap2 = "0.9.10"
softbuffer = "0.4.8"
winit = "0.31.0-beta.2"

[workspace.lints.clippy]
new_without_default = "allow"
