name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu
          components: rustfmt, clippy
      - name: Checks
        run: |
          cargo fmt --check
          cargo clippy --all-targets -- -D warnings

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-gnu,i686-pc-windows-msvc,x86_64-pc-windows-gnu,x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --all-targets

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-unknown-linux-gnu,i686-unknown-linux-musl,x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl,x86_64-linux-android
      - name: Build
        run: cargo build --all-targets
