name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Checks
      env:
        CLIPPY_OPTS: --all-targets
      run: |
        cargo fmt --check
        cargo clippy $CLIPPY_OPTS
    - name: Run tests
      run: cargo test --all-features
    - name: Build
      run: cargo build --all-features
